[book]
title = "BitOMC Handbook"
language = "en"
src = "src"

[build]
build-dir = "build"
create-missing = false
extra-watch-dirs = ["po"]

[output.html]
cname = "docs.bitomc.org"
default-theme = "coal"
git-repository-url = "https://github.com/BitOMC/BitOMC"
preferred-dark-theme = "coal"
additional-css = ["language-picker.css"]

[output.linkcheck]

[preprocessor.gettext]
after = ["links"]
